### ISSUE TITLE
add naturaldocs documentation to `src/bookmarks.js`

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/modules#64]
Right now, the Bookmarks module doesn't show up on http://remotestorage.io/modules/code/files2/overview-txt.html because it is lacking naturaldocs.

I added JSON schema spec links to remotestorage.io, but they now point to 404s in the documentation, e.g.: http://remotestorage.io/spec/modules/bookmarks/archive-bookmark/

**Comment by skddc** [comment]
Not sure when I documented it, but I was pretty sure before this issue. Maybe not. Anyway, it's documented now, so I'm closing it. Re-open if I missed something!

**Comment by michielbdejong** [comment]
I fixed it in that commit, but accidentally wrote "fix" instead of "fixes", which is why the issues didn't close automatically (the keywords that work are [close, closes, closed, fixes, fixed](https://github.com/blog/1386-closing-issues-via-commit-messages)).

**Comment by skddc** [comment]
May I ask why the docs didn't show up, for future reference? Did we just forget to compile them?

**Comment by michielbdejong** [comment]
They didn't show up because they didn't exist - at least in master. :) You say you're "pretty sure" you added them before https://github.com/remotestorage/modules/blame/b00d3859c7549118e807a70af1cd5bfbcaeb6330/src/bookmarks.js but apparently you either didn't, or didn't push them, or in a different branch. If you want to know for sure, then check git history.

**Comment by skddc** [comment]
Ah, I missed the file on the bottom of the page here. Thought it was just docs.

Thanks.
