### ISSUE TITLE
Support installing RemoteStorage modules through Bower

### ISSUE THREAD

**Issue by Vinnl** [remotestorage/modules#70]
In order to make it easier to re-use common modules, it would be nice if we could install them through Bower as well. Preferably a package per module, but with the list of modules this small it would already be a useful improvement if all of them could be installed and managed at once using Bower.

**Comment by skddc** [comment]
Good point!

If we want to have one bower package per module, we'd need to have them in separate repos, right?

**Comment by Vinnl** [comment]
I think so, yes, although those repositories could of course be auto-generated.

**Comment by skddc** [comment]
Yes, auto-generating would work I guess.

No matter if putting them in separate repos or not, we still need a better way for sharing functionality among modules and defining dependencies. I personally would very much prefer to forgo any hacks and move to ES6 modules for that asap. As soon as we set up a build system (which is unavoidable for ES5 compat), we could then also implement bower package generation in that.

**Comment by skddc** [comment]
.... for now I guess just adding a simple package config and distributing the repo as is might be the way to go.

**Comment by Vinnl** [comment]
Cool, I've created a pull request for that. Not that package.json referred to remotestorage 0.10.3 as a dependency, but only 0.11.0 and 0.10.2 are available on Bower - I've listed the latter as the Bower dependency now.

**Comment by skddc** [comment]
> Note that package.json referred to remotestorage 0.10.3 as a dependency

Oh, that's an outdated config then. We need to add testing with modules and updating that config to the rs.js release checklist.

**Comment by skddc** [comment]
> I've listed the latter as the Bower dependency now.

I think `0.11.0` doesn't contain breaking changes that would make modules incompatible.

**Comment by skddc** [comment]
As @Vinnl stated earlier, adding this file doesn't fix the situation. Re-opened it therefore until someone could actually install it via Bower and use it.

**Comment by skddc** [comment]
Did the registration and tested installing. Looks good.
