### ISSUE TITLE
Remove in documents module throws error

### ISSUE THREAD

**Issue by vision89** [remotestorage/modules#82]
In documents.js remove function takes in an id then calls itself recursively until it blows the stack.

**Comment by skddc** [comment]
@jorinvo just picked up development of [Litewrite](https://github.com/litewrite/litewrite/) again, and plans to update the documents module in the process.

**Comment by taophp** [comment]
@skddc What tip ? This is a bug that needs to be fixed! 
see [documents.js](https://github.com/remotestorage/modules/blob/master/src/documents.js) lines 133 to 135:
```javascript
remove: function(id) {
      return this.remove(id.toString());
},
```
This CANNOT work.

**Comment by skddc** [comment]
RemoteStorage.js modules are developed by the app authors who use them. In this case that's @jorinvo. I cannot speak for him, but as he hasn't responded here yet, the quickest way to get it fixed is to do it yourself I think.

You can ask people on IRC (#remotestorage on Freenode) or [the forums](http://community.remotestorage.io/) or here on GitHub anytime if you have any questions whatsoever, and they will gladly help you along the way.

**Comment by skddc** [comment]
I had a quick look just now, and it looks like these methods are added to the `BaseClient` instance (create with `scope` above), so it'll likely work by just renaming the function to something other than `remove` (which is `BaseClient`'s own function for deleting objects).

**Comment by taophp** [comment]
@skddc: well, renaming the function that way seems to work:
```javascript
remove: function(id) {
      return this.remove(id.toString());
},
```
So I could do it myself. But, before forking, fixing and request a merge, two questions:

* is there a naming convention I must follow ? i.e. what should be the new name of the function ?
* who will update https://remotestorage.github.io/modules/files/documents-js.html#listMethods.remove ? should I also do it by forking [remotestorage.io](https://github.com/remotestorage/remotestorage.io) the "[DEPRECATED] Old RS website" ?

**Comment by skddc** [comment]
> is there a naming convention I must follow ? i.e. what should be the new name of the function ?

No, there are currently no conventions for modules. One thing you can't do however, is name it `delete`, because that's a reserved keyword.

> who will update https://remotestorage.github.io/modules/files/documents-js.html#listMethods.remove ?

The docs are generated from the code comments in this repository. I would update them after merging a pull request.

**Comment by skddc** [comment]
@jorinvo It would also be interesting to know how this works in Litewrite, because I can certainly delete documents there.

**Comment by taophp** [comment]
> One thing you can't do however, is name it delete, because that's a reserved keyword.
So is `destroy` suitable ?

**Comment by skddc** [comment]
@taophp Thanks for the PR! Much appreciated.

We looked at it in more detail, and @galfert found out that the module used in Litewrite doesn't even contain the function anymore, which makes sense to me. It only transforms the passed ID (filename) into a string, but one should pass it a string in the first place and just use the `BaseClient` remove function instead of a custom one then.

So I would propose removing it entirely and using `remove` as intended in your and other codebases. What do you think?

**Comment by taophp** [comment]
This soluiton is fine for me!

**Comment by skddc** [comment]
Ok, great. Want to get your name credited in the codebase for that fix by opening another PR? :)

**Comment by taophp** [comment]
Oh, I didn't expect so much for so few. I'll do that tonight!

**Comment by skddc** [comment]
Thanks. I merged manually and edited the commit message: https://github.com/remotestorage/modules/commit/9e9ca1a1366125740ebbe72d724ace2c92433405

**Comment by taophp** [comment]
I do not know and do not understand why, but the removed function `remove` is back again... That may explain why you did see any changes in the documentation...

**Comment by taophp** [comment]
It seems to add occur then : https://github.com/remotestorage/modules/commit/6d10b97109a5b775cc81a4a99735b1f263832818

**Comment by skddc** [comment]
Uh, wow. That's strange! Will check it out.

**Comment by taophp** [comment]
@skddc any news about that ?

**Comment by skddc** [comment]
Stupid me. The original commit removed it from our build directory, called "dist", instead of the source directory, called "source". So the changes were overwritten by my subsequent build.

The reason we have both source and build files is that we can use ES6 syntax in the source files, including ES module imports. The source code is transpiled to ES5 and bundled into one file in "dist" when the build command is run.

**Comment by taophp** [comment]
OK, I get it. Fine for me. Happy to see it fixed now.
