### ISSUE TITLE
[chat-messages] Add XMPP

### ISSUE THREAD

**Issue by skddc** [remotestorage/modules#92]
Currently, some things are hardcoded for IRC. We're starting to use this with XMPP MUC ourselves, so we need support for that (and other types in general).

**Comment by skddc** [comment]
Note from afk convo: we should actually dismiss the `/irc/` base directory altogether and only use custom aliases. The whole idea is, that you can switch backends anytime and retain your same history and settings. So it doesn't make sense to have /irc or /xmpp or anything like that.

**Comment by skddc** [comment]
XMPP support is in. This is a somewhat breaking change, as it will store archives without the server/protocol type in the document path from now on.

**Comment by silverbucket** [comment]
Sorry for jumping on late, just wondering. why not use something more generic, like just `uri` and have the `uri` itself define what protocol it was received from?

**Comment by skddc** [comment]
I didn't think about it, because the URIs are actually quite different. But the scheme is always the first element before a colon, of course, so one can easily implement different ways of parsing the same thing.

Anyone else has opinions on this? I'm fairly neutral to which option is better.

**Comment by silverbucket** [comment]
@skddc that's what I do with sockethub user-identifiers, to route messages and uniquely represent each platform+user+room

**Comment by skddc** [comment]
Except then the context is clearer. As I said, this URI could refer to various different things in the archive's context.

I think the closest meaning would be the source of the message. So perhaps something along the lines of `sourceURI` would make sense. Sounds weird to me though.

**Comment by silverbucket** [comment]
In the AS-like objects in sockethub they are referred to as `actor.id` and `target.id` which could be a platform+room without a user, or a user+platform+room, or without a room if they are direct messages.
